### ISSUE TITLE
Additional comments on shallow clones

### ISSUE THREAD

**Issue by osowskit** [jonico/speedup-builds#1]
https://github.com/github/solutions-engineering/issues/3045#issuecomment-246269223

> > I've seen some of the technical discussion [about shallow clones] before but want to know the trade off on build times. Even if it is worse for GHE itself, I am hesitant at recommending shallow clones for everything if they reduce network traffic and decrease build times.
> 
> @github/git-infrastructure would you be able to provide insight or recommendations here?

Ultimately there is no substitute for the user running benchmarks in their own environment. But as general rules, I think the following will be pretty consistently true. Assuming the common scenario that CI hosts need up-to-date branch tips to run tests on:
1. The best performance (in terms of GHE load, client load, bandwidth usage, and wall-clock-time) would be to do a full clone of the repository once, and afterwards use `git fetch` to bring it up to date prior to each test run. Assuming that the clone is updated often, most of the fetches will only have to get a few Git objects (because relatively few objects typically change from commit to commit), and the GHE server is highly optimized for figuring out what objects are needed and sending them. What's more, if many CI servers are doing the same fetches simultaneously, the GHE server will automatically detect this fact and send them all the same data without having to compute it multiple times.
2. If you really must start with a fresh repository each time on the build server (i.e., you can't fetch into an existing repository), then it is probably faster to do a shallow clone than a full clone, and this will also save bandwidth and disk space on the client. But beware, this will probably create more CPU load (by, say, a factor of "a few") on the server than a full clone.
3. We recommend _against_ fetching into a shallow clone as part of CI. This would combine the disadvantages of both of the methods listed above: it would cause considerably more CPU load on the GHE server, without (over the long run) reducing bandwidth usage. If for some reason you must fetch into a shallow clone, be sure that the `git fetch` command also uses the `--depth=1` option; otherwise, the fetch is likely to cause big chunks of unneeded Git history to be fetched in a way that is very expensive to the GHE server.

There are some possibilities for making full clones even faster (for example, having one local clone fetch from GHE then having multiple local clones clone/fetch from that one), but they would be more work to set up, and are probably not worth it except in the biggest CI setups.

**Comment by jonico** [comment]
thanks @osowskit, adjusted ```README.md``` to make more clear under which circumstances a shallow clone would help
